import type { Metadata } from "next"
import { Header, Footer } from "@ui"

import "@theme/_reset.scss"
import "@theme/_variables.scss"
import "@theme/_mixins.scss"
import "@theme/_general.scss"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}

// className={`${geistSans.variable} ${geistMono.variable}`}
