export { Page } from "./page"
export { Header } from "./header"
export { Footer } from "./footer"
export * from "./primitives"
export * from "./home"
export * from "./transactions"
export * from "./newsIndex"
export * from "./testimonials"
export * from "./portfolio"
